version: '3'
services: 
  selenium-node1:
    image: 'selenium/node-chrome'
    volumes:
      - /tmp/robot_images:/home/seluser
    depends_on: 
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
  selenium-node2:
    image: 'selenium/node-chrome'
    volumes:
      - /tmp/robot_images:/home/seluser
    depends_on: 
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
  selenium-hub:
    image: 'selenium/hub'
    ports:
      - "4444:4444"
  